name: unit tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          # Install a specific version of uv.
          version: "0.9.11"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version-file: ".python-version"

      - name: Install dependencies and check code
        run: |
          cd aieng-forecasting
          uv venv .venv
          source .venv/bin/activate
          uv sync --all-extras --dev --all-packages
          uv run pytest -m "not integration_test" tests ../implementations/tests
